# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ImageUploader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'ObjectMapper'
  pod 'IGRPhotoTweaks'
  pod 'Kingfisher'
  pod 'YPImagePicker'
  pod 'AppImageViewer'
  pod 'SVProgressHUD'

  # Pods for ImageUploader

  target 'ImageUploaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageUploaderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
